### ISSUE TITLE
Docker push error "Error:Error pushing to registry: Authentication is required."

### ISSUE THREAD

**Issue by gnudeep** [fabric8io/docker-client#16]
I try to push a docker image to a private registry. I tried various Auth configs but, I still get the following error.

The push refers to a repository [image1] (len: 2)
Error:Error pushing to registry: Authentication is required.

docker-client : 1.0.4

Client version: 1.7.1
Client API version: 1.19
Go version (client): go1.4.2
Git commit (client): 786b29d
OS/Arch (client): linux/amd64
Server version: 1.7.1
Server API version: 1.19
Go version (server): go1.4.2
Git commit (server): 786b29d
OS/Arch (server): linux/amd64

**Comment by iocanel** [comment]
Thanks for the feedback!

Can you please provide some more information about the private registry you are trying to push to and maybe share some of the code you are using?

**Comment by gnudeep** [comment]
My image name looks like this:

registry.docker.myperl.org:5000/deep/image1
  
I am using the docker-client ImageBuileExample class.

client.image().withName(image).tag().inRepository("registry.docker.myperl.org:5000/deep/image1").force().withTagName("v2");

My local docker is started like this:

 /usr/bin/docker -d -H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock --insecure-registry registry.docker.myperl.org:5000

**Comment by iocanel** [comment]
Great!

The ImageBuileExample doesn't directly handle authconfig (it expects to find it in ~/.docker/config.json) so you will either have to create it programmatically, or ensure that ~/.docker/config.json exists (its generated by docker login).

An example of how to create the config programmatically.

        Config config = new ConfigBuilder()
                .withMasterUrl(dokcerHost)
                .addToAuthConfigs("registry.docker.myperl.org:5000", new AuthConfig("", "someone@somewhere.com", "somepass", "registry.docker.myperl.org:5000", "someuser"))
                .build();
        DockerClient client = new DefaultDockerClient(config);

Also I would make sure that the push command would look like:

client.image().withName("registry.docker.myperl.org:5000/deep/image1")....toRegistry();

**Comment by gnudeep** [comment]
It worked after fixing the following line:
handle = client.image().withName(image).push().usingListener(new EventListener() {...}).toRegistry();

by setting the correct remote registry.
client.image().withName("registry.docker.myperl.org:5000/deep/image1")....toRegistry();

Thankx @iocanel

**Comment by iocanel** [comment]
I think that I need to improve the example so that its more self explanatory.

**Comment by iocanel** [comment]
Added 9ea79e8bc25f03a6cda909b31fac929828bc37ed. I think this can close now.
