### ISSUE TITLE
Cannot start the docker-model bundle because it imports its own packages.

### ISSUE THREAD

**Issue by gnudeep** [fabric8io/docker-client#19]
I could not start the docker-model bundle because it imports its own packages.
osgi> ss docker
69	INSTALLED   io.fabric8.docker-model_1.0.4

osgi> start 69
gogo: BundleException: The bundle "io.fabric8.docker-model_1.0.4 [69]" could not be resolved. Reason: Missing Constraint: Import-Package: io.fabric8.docker.api.model.serialize; version="0.0.0"

I fixed the issue by excluding it own packages in import section.

  <osgi.import>!io.fabric8.docker.api.*,*;resolution:=optional</osgi.import>

**Comment by iocanel** [comment]
Thanks for the feedback and the suggestion.

**Comment by iocanel** [comment]
OSGi metadata have been fixed.
Added integration tests and features for Apache Karaf.

Note: docker-client depends on artifacts that are not bundles and are not designed to work on OSGi. Thus it was necessary to wrap them inside the docker-client bundle. So now, the docker-client module produces two artifacts a plain jar and an OSGi uberbundle with the bundle classifier.
