### ISSUE TITLE
Docker push fails when I try to upload 556.1 MB image to my local repository via dcocker-client API

### ISSUE THREAD

**Issue by gnudeep** [fabric8io/docker-client#29]
Docker push fails when I try to upload 556.1 MB image to my local repository via dcocker-client API. I can upload the same image via my docker CLI without any issue but it takes time.

I think docker-client times out before the upload complete and give error to the application.

Is there any way to increase the docker-client timeout.

Thanks,
Deependra.

**Comment by iocanel** [comment]
The timeout for image push is by default 10 mins: https://github.com/fabric8io/docker-client/blob/6caffcf6b946b8b149c0ab44fbe165fa09386274/client/src/main/java/io/fabric8/docker/client/Config.java#L99

It can be changed globally in the Config object with code like:

         Config config = new ConfigBuilder()
                .withDockerUrl(dokcerHost)
                .withImagePushTimeout(customTimeout)
                .build();

        DockerClient client = new DefaultDockerClient(config);

**Comment by gnudeep** [comment]
I increased  ConnectionTimeout, RequestTimeout and PushTimeout but still API time out around 60 seconds.

Config config = new ConfigBuilder()
                .withMasterUrl(DockerOpClientConstants.DEFAULT_DOCKER_URL)
                .withConnectionTimeout(10*60*1000)
                .withRequestTimeout(10*60*1000)
                .withImagePushTimeout(10*60*1000)
                .build();

**Comment by iocanel** [comment]
Can you please provide a stack trace?

**Comment by gnudeep** [comment]
No stack trace. Just onError triggers without any message.

**Comment by gnudeep** [comment]
There was an issue in my system.

Suggested code works.

**Comment by iocanel** [comment]
That's great to hear!
