### ISSUE TITLE
docker-client 1.0.10 bundle is not in the Central Repository

### ISSUE THREAD

**Issue by gnudeep** [fabric8io/docker-client#34]
docker-client 1.0.10 bundle is not in the Central Repository. 

The docker-client bundle created by the build packaged dependencies. Can we have a clean osgi bundle from the next build and upload it into the Maven Central Repos.

Thanks,
Deependra.

**Comment by iocanel** [comment]
It's here: http://repo1.maven.org/maven2/io/fabric8/docker-client/1.0.10/docker-client-1.0.10-bundle.jar

Please note that the docker-client itself is not a bundle, but we do ship a bundelized artefact with the same maven coordinates and using "bundle" as classifier. 

As I am terrible at explaining things, hopefully this will make it more clear:

    <dependency>
        <groupId>io.fabric8</groupId>
        <artifactId>docker-client</artifactId>
        <version>1.0.10</version>
        <classififer>bundle</classifier>
    </dependency>

**Comment by gnudeep** [comment]
Thank you for the explanation.

I have another question. Why docker-client bundles other packages like org.newsclub

**Comment by iocanel** [comment]
AFAIR, those packages are transitives for a lib we use to support unix sockets. They are not bundles themselves, so we uberbundle them.

I don't fancy that approach myself, so any kind of improvements there are more than welcome :-)

**Comment by gnudeep** [comment]
Thank you for the clarification.
