### ISSUE TITLE
Implement exec, image and network in DefaultDockerClient

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-client#41]
The methods for exec, image and network returns null in DefaultDockerClient:

    @Override
    public ExecInterface exec() {
        return null;
    }

    @Override
    public ImageInterface image() {
        return new ImageOperationImpl(client, configuration);
    }

    @Override
    public NetworkInterface network() {
        return null;
    }

    @Override
    public VolumeInterface volume() {
        return null;
    }

**Comment by iocanel** [comment]
@Khazrak thanks for reporting, I'll have a look asap.

**Comment by Khazrak** [comment]
I started playing what would be needed to fix this, if you look at: https://github.com/Khazrak/docker-client
Then the "list all networks" works now. A thing to note is that the network API doesn't have "json" in it as container API does. ex: 
GET /networks
GET /containers/json
GET /images/json
GET /volumes
So I removed JSON_OPERATION and put EMPTY in the constructor for ListNetwork.

**Comment by iocanel** [comment]
@Khazrak: that's is so great :-)

When you have a pull request ready, I'll review/merge/release asap.
