### ISSUE TITLE
Provide an option to disable certificate check

### ISSUE THREAD

**Issue by apupier** [fabric8io/docker-client#42]
When using the docker-maven-plugin using CDK and Docker Tools on Windows 10, I have a certificate issue.

it would be nice to have an option to disable the certificate check.

You can find the log here: https://gist.github.com/apupier/cdd837afda96b6bc878e739559f67a92

**Comment by jimmidyson** [comment]
Think that the `DOCKER_TLS_VERIFY` & `DOCKER_CERT_PATH` env vars should be supported - they're pretty standard now.
