### ISSUE TITLE
Can't Expose ports

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-client#48]
When trying to expose ports with the ContainerCreateRequestBuilder and ".addToExposedPorts(1337, Protocol.TCP)" I get this Exception:

`Caused by: com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class java.lang.Object and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) ) (through reference chain: io.fabric8.docker.api.model.EditableContainerCreateRequest["ExposedPorts"]->java.util.HashMap["1337/tcp"])`

It that it can't serialize "new Object()" from ExposedPortSerializer class

**Comment by iocanel** [comment]
Let me have a look
