### ISSUE TITLE
Client slow on 2 commands or more (probably timeout)

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-client#51]
If you run several commands on the client (one after the other) it is really slow. Every command after the first takes 30s (a timeout?). If you close and open the client between every command then this does not occur.

I attached a junit test that creates a container, starts it, stops it and removes it. One test with closing the client between every command (fast) and one test without it (slow), the speeds are:
fast: 1s 121ms
slow: 1m 30s 550ms

[Speed.txt](https://github.com/fabric8io/docker-client/files/278988/Speed.txt)

**Comment by iocanel** [comment]
While I am still looking at #50 could you please try without using the a unix socket and see if it makes any difference so that we can narrow it down a little bit?

**Comment by rhuss** [comment]
@Khazrak are you using a Linux docker daemon or the new Docker for Mac over the unix socket ?

**Comment by rhuss** [comment]
I could reproduce it on Docker for Mac which uses a Unix Socket as well. Breaking while debugging shows that the test hangs in a read on the Unix Socket. I set a breakpoint on IOExceptions and saw that the UnixSocket read throws an exception like:

```
Resource temporarily unavailable at Socket[addr=0.0.0.0/0.0.0.0,port=0,localport=0][fd=java.io.FileDescriptor@1880249c; file=/Users/roland/Library/Containers/com.docker.docker/Data/s60; connected=true; bound=false]
```

**Comment by Khazrak** [comment]
I'm using Linux docker daemon (Ubuntu 16.04 also tested on Ubuntu 14.04).
I also tested on the tcp insted of unix socket and can verify that the problem is contained in the unix socker (tcp works fast)

**Comment by iocanel** [comment]
So with @rhuss fix it should be working ok now.

@Khazrak do you want to give it a spin?

**Comment by Khazrak** [comment]
Tried it and it worked great

**Comment by iocanel** [comment]
perfect!
