### ISSUE TITLE
Problem with reading logs of container

### ISSUE THREAD

**Issue by Khazrak** [fabric8io/docker-client#58]
When using the code from the attached [LogTest.txt](https://github.com/fabric8io/docker-client/files/281871/LogTest.txt)

I get the Exception:
[OkHttp http://localhost/containers/my_container/logs?follow=false&stdout=true&stderr=false] ERROR io.fabric8.docker.client.impl.ContainerOutputHandle - OK
java.net.ProtocolException: Expected HTTP 101 response but was '200 OK'

Full stack trace: [log.txt](https://github.com/fabric8io/docker-client/files/281870/log.txt)

And this is mentioned a bit on the official api page:
[https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#3-2-hijacking](https://docs.docker.com/engine/reference/api/docker_remote_api_v1.21/#3-2-hijacking)

The api-call is correctly formed but it doesn't upgrade from 200 to 101, is the right headers sent?

**Comment by iocanel** [comment]
I think that the headers are ok. Let me experiment with it a little bit.

**Comment by iocanel** [comment]
@Khazrak: just pushed a fix for that. Let me know how this works for you :-)
