### ISSUE TITLE
problem when inspecting a container

### ISSUE THREAD

**Issue by gengweifeng** [fabric8io/docker-client#59]
Execuse me, I want to get some envs in a container. 
But when I inspect a container using the dockerclient api, there is a exception that desribes:

> Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of io.fabric8.docker.api.model.LxcConfig out of START_ARRAY token at Source: buffer (com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource@71def8f8 ) .inputStream(); line: 1, column: 1193 (through reference chain: io.fabric8.docker.api.model.ContainerInspect["HostConfig"]->io.fabric8.docker.api.model.HostConfig["LxcConf"])

my java codes: 

> dockerClient.container().withName(containerId).inspect().getConfig().getEnv()

when I use command-line "docker inspect containerId", the result is:

> [
  {
      [...]
      "HostConfig": {
          [...]
          "LxcConf": [],
          [...]
      }
      [...]
  }
]

what did I mistake or it is a bug?

**Comment by iocanel** [comment]
What you are doing is fine! Its either a bug or a version mismatch!

**Comment by gengweifeng** [comment]
Thank you ! so, what can I do next to solve this problem? Or waitting?

**Comment by iocanel** [comment]
What version of docker daemon are you using?

**Comment by gengweifeng** [comment]
the server version is 1.9.0 via command-line "docker info" and the library version 1.0.16

**Comment by iocanel** [comment]
Yeah, its a bug! I'll try to fix and release asap.

**Comment by gengweifeng** [comment]
OK, thank you very much! I will be here to waiting for you!   ^_^

**Comment by iocanel** [comment]
@gengweifeng: Ok this seems to work fine here, so I guess that there is something specific in the particular container that breaks things.

It would help if you could paste the exact json that gets displayed by docker inspect.

Does it do the same for all containers, or its something that just happens for a specific one?

**Comment by gengweifeng** [comment]
I have done as what you said, I made another two images and created containers. But there also has this exception. I upload [docker inspect result.txt](https://github.com/fabric8io/docker-client/files/292910/docker.inspect.result.txt) as the result of command-line "docker inspect containerId" and upload [exception.txt](https://github.com/fabric8io/docker-client/files/292914/exception.txt) as the detail result of e.printStackTrace. Can you help check it wrong or right, please?
By the way, I run docker in my vmware workstation, does it matter?

**Comment by iocanel** [comment]
Yes vmware workstation should be fine!

Let me test with your output and I'll get back to you!

**Comment by jimmidyson** [comment]
So the reason is because `LxcConfig` has no exported fields - see https://github.com/docker/docker/blob/v1.9.1/runconfig/hostconfig.go#L159 - so the generator just treats it like an empty struct. You're going to have to handle that specially, perhaps manually updating the JSON schema after generation or creating the type manually. You'll also need to ensure it follows the same (un)marshalling rules.

**Comment by gengweifeng** [comment]
So, the `LxcConfig` must not be empty? What I should do is that after creating containers I must update the `LxcConfig` fileds manually to ensure it not empty?Eh, it doesn't sound like a good job! Is it the only choice?

**Comment by jimmidyson** [comment]
No that is not a good option. I'll discuss with @iocanel the best way but this is a problem in the generation of the client model that we need to fix so this just works for you.

**Comment by iocanel** [comment]
@jimmidyson: thanks for the explanation. I guess that we have to create a custom type with a custom deserialiser that will mimic the golang one.

**Comment by jimmidyson** [comment]
Yeah - think we did something similar for IntOrString type in kubernetes model.

**Comment by iocanel** [comment]
I pushed a fix and a unit test!

@gengweifeng: can u tell me how this works for you?

**Comment by gengweifeng** [comment]
@iocanel Can you give me the fixed jar libray, please? I'm so sorry to say that I don't know how to test it works or not just cross the thing above! It's a pity!

**Comment by gengweifeng** [comment]
OK, I have test the fixed code, it works well. I can get the envs through the inspect interface and there isn't exception! You can release it! Thank you very much!
