### ISSUE TITLE
Reading DOCKER_HOST environment variable with scheme 'tcp' results in invalid URL

### ISSUE THREAD

**Issue by thxmasj** [fabric8io/docker-client#65]
CLI-docker apparently requires the DOCKER_HOST environment variable to use a 'tcp' scheme, while this client requires the scheme to be 'http' or 'https'. The conversion seems to be broken. I have an environment variable DOCKER_HOST with the value 'tcp://myhost:2376', which is converted to 'https:///myhost:2376'. The problem is io.fabric8.docker.client.utils.URLUtils#URL_PATTERN (duplicate character '/' in character class).

**Comment by iocanel** [comment]
@thxmasj thanks for reporting that. I'll fix that asap unless you want to send in a pr.

**Comment by thxmasj** [comment]
@iocanel I would be happy to do that, but unfortunately I cannot get the master HEAD to build right now:
```
Failed tests:   testMatching(io.fabric8.docker.client.utils.DockerIgnorePathMatcherTest)
```

**Comment by iocanel** [comment]
Here it builds fine. Can you create a new issue for that and maybe attach more information?

**Comment by thxmasj** [comment]
@iocanel Seems like my Cygwin environment caused the failing test. It works OK when building in a  maven:3.3.9-jdk-8 container. Created a PR, but I was apparently too slow. :-P

**Comment by iocanel** [comment]
@thxmasj no worries. I merged your PR :-)

Thanks for taking the time to contribute back!
